[package]
name = "jvm-macro"
version = "0.1.0"
authors = ["Daniel Lewiński <nerull@craftsoft.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true


[dependencies]
serde = { version = "1.0", features = ["derive"] }
rustc-serialize = "0.3"
quote = "1.0"
syn = { version = "1.0", features = ["full", "fold", "parsing"] }
proc-macro2  = "1.0"

